services:
  - type: web
    name: crypto-rebalancer-api
    env: python
    rootDir: api
    buildCommand: cd .. && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-rebalancer-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://crypto-rebalancer-ui.netlify.app

  - type: worker
    name: crypto-rebalancer-bot
    env: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-rebalancer-db
          property: connectionString
      - key: THREE_COMMAS_API_KEY
        sync: false
      - key: THREE_COMMAS_API_SECRET
        sync: false
      - key: COINGECKO_API_KEY
        sync: false

databases:
  - name: crypto-rebalancer-db
    databaseName: cryptorebalancer
    plan: free
    ipAllowList: [] # only allow internal connections
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-rebalancer-db
          property: connectionString

databases:
  - name: crypto-rebalancer-db
    databaseName: cryptorebalancer
    plan: free
